config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  post '/characters/:id/claim', to: 'characters#claim'
  post '/characters/:id/release', to: 'characters#release'
  resources :characters

  resources :users, path: 'accounts'

  resources :teams
  resources :events
  resources :computed_events, path: 'signups'
  resources :raid_progressions
  resources :raid_preferences
  resources :roster_rotations

  put '/character_events/signup/:id', to: 'character_events#update'
  put '/character_events/rotation/:id', to: 'character_events#rotation'
  resources :character_events, only: [:index]

  resources :event_statuses, only: [:index], path: "signup_status"

  root 'computed_events#index'

end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        - if can? :index, User or can? :index, Team or can? :index, Event
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown"
              = "Admin"
              span.caret
            ul.dropdown-menu role="menu"
              li = link_to("Accounts", users_path) if can? :index, User
              li = link_to("Teams", teams_path) if can? :index, Team
              li = link_to("Event Rules", events_path) if can? :index, Event
        li = link_to("Characters", characters_path) if can? :index, Character
        li = link_to("Raid Progression", raid_progressions_path) if can? :index, BossPreference
        li = link_to("Event Signup", computed_events_path) if can? :index, ComputedEvent
        li = link_to("Signup Status", event_statuses_path) if can? :index, EventStatus
        li = link_to("Roster Rotation", roster_rotations_path) if can? :index, ComputedEvent
      .pull-right
        - if user_signed_in?
          = link_to 'Edit account', edit_user_registration_path, class: 'navbar-brand'
          = link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'navbar-brand'
        - else
          = link_to 'Sign in', new_user_session_path, class: 'navbar-brand'
          = link_to 'Sign up', new_user_registration_path, class: 'navbar-brand'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Exterminatus Raid Signup'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Exterminatus Rails'}"
    == stylesheet_link_tag "application", media: "all"
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield